# Where are all the schema files located? globs are supported eg  src/**/*.graphql
schema:
  - yy-go-schema-template/schema/*.graphql

# Where should the generated server code go?
exec:
  filename: graphql/generated/generated.go
  package: generated

# Where should any generated models go?
model:
  filename: model/graphql_generated.go
  package: model

# Where should the resolver implementations go?
resolver:
  layout: follow-schema
  dir: graphql
  package: graphql

struct_tag: json

autobind:
  - github.com/Yoshioka9709/yy-go-backend-template/model

models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
  String:
    model:
      - github.com/99designs/gqlgen/graphql.String
      - github.com/Yoshioka9709/yy-go-backend-template/model.Cursor
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Timestamp:
    model:
      - github.com/99designs/gqlgen/graphql.Time
