version: '4'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    entrypoint: ["java"]
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
    ports:
      - 8000:8000
    volumes:
      - dynamodb-local:/home/dynamodblocal

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8002:8001
    depends_on:
      - dynamodb-local

  redis:
    image: redis:6.0-alpine # ElastiCache Redis version
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db

volumes:
  dynamodb-local:
    driver: local
  redis:
    driver: local
  redisinsight:
    driver: local