version: '3'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    entrypoint: ["java"]
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
    ports:
      - 8000:8000
    volumes:
      - dynamodb-local:/home/dynamodblocal

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8002:8001
    depends_on:
      - dynamodb-local

volumes:
  dynamodb-local:
    driver: local
